# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-Bank-NL-CLIEOP03
version:      0.02
version_from: lib/Finance/Bank/NL/CLIEOP03.pm
installdirs:  site
requires:
    Carp:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
